/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl */

#ifndef _Included_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
#define _Included_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
#ifdef __cplusplus
extern "C" {
#endif
#undef POWER_ON
#define POWER_ON 1L
#undef POWER_OFF
#define POWER_OFF 0L

#define GET_RESPONSE 1
#define IGNORE_RESPONSE 0

#define MAX_DEVICES 10

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeInit
  (JNIEnv *env, jobject obj);

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeStartCP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeStartCP
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeStopCP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeStopCP
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeGetPower
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeGetPower
  (JNIEnv *, jobject, jstring jsUDN);

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeSetPower
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeSetPower
  (JNIEnv *, jobject, jstring jsUDN, jboolean);

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeGetLoadLevel
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeGetLoadLevel
  (JNIEnv *, jobject, jstring jsUDN);

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeSetLoadLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeSetLoadLevel
  (JNIEnv *, jobject, jstring jsUDN, jint);

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeAllOn
 * Signature: ()Ledu/cmu/hcii/puc/devices/UPnP/IntelLight/LightEvent;
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeAllOn
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl
 * Method:    nativeAllOff
 * Signature: ()Ledu/cmu/hcii/puc/devices/UPnP/IntelLight/LightEvent;
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_IntelLight_LightControl_nativeAllOff
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
