/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_hcii_puc_devices_DVCamera */

#ifndef _Included_edu_cmu_hcii_puc_devices_DVCamera
#define _Included_edu_cmu_hcii_puc_devices_DVCamera
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_cmu_hcii_puc_devices_DVCamera_POWER_ON
#define edu_cmu_hcii_puc_devices_DVCamera_POWER_ON 1L
#undef edu_cmu_hcii_puc_devices_DVCamera_POWER_OFF
#define edu_cmu_hcii_puc_devices_DVCamera_POWER_OFF 0L
#undef edu_cmu_hcii_puc_devices_DVCamera_DEVICE_MODE_CAMERA
#define edu_cmu_hcii_puc_devices_DVCamera_DEVICE_MODE_CAMERA 0L
#undef edu_cmu_hcii_puc_devices_DVCamera_DEVICE_MODE_VCR
#define edu_cmu_hcii_puc_devices_DVCamera_DEVICE_MODE_VCR 1L
#undef edu_cmu_hcii_puc_devices_DVCamera_MEDIA_VHS
#define edu_cmu_hcii_puc_devices_DVCamera_MEDIA_VHS 1L
#undef edu_cmu_hcii_puc_devices_DVCamera_MEDIA_DV
#define edu_cmu_hcii_puc_devices_DVCamera_MEDIA_DV 2L
#undef edu_cmu_hcii_puc_devices_DVCamera_MEDIA_UNKNOWN
#define edu_cmu_hcii_puc_devices_DVCamera_MEDIA_UNKNOWN 3L
#undef edu_cmu_hcii_puc_devices_DVCamera_MEDIA_NONE
#define edu_cmu_hcii_puc_devices_DVCamera_MEDIA_NONE 4L
#undef edu_cmu_hcii_puc_devices_DVCamera_T_MODE_PLAY
#define edu_cmu_hcii_puc_devices_DVCamera_T_MODE_PLAY 1L
#undef edu_cmu_hcii_puc_devices_DVCamera_T_MODE_STOP
#define edu_cmu_hcii_puc_devices_DVCamera_T_MODE_STOP 2L
#undef edu_cmu_hcii_puc_devices_DVCamera_T_MODE_PAUSE
#define edu_cmu_hcii_puc_devices_DVCamera_T_MODE_PAUSE 3L
#undef edu_cmu_hcii_puc_devices_DVCamera_T_MODE_FF
#define edu_cmu_hcii_puc_devices_DVCamera_T_MODE_FF 4L
#undef edu_cmu_hcii_puc_devices_DVCamera_T_MODE_REW
#define edu_cmu_hcii_puc_devices_DVCamera_T_MODE_REW 5L
#undef edu_cmu_hcii_puc_devices_DVCamera_T_MODE_RECORD
#define edu_cmu_hcii_puc_devices_DVCamera_T_MODE_RECORD 6L
/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_init
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeIsPowerOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeIsPowerOn
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeGetDeviceMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeGetDeviceMode
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeGetMedia
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeGetMedia
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeGetAVCVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeGetAVCVersion
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeGetFrameRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeGetFrameRate
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeGetPort
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeGetPort
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeGetTimecode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeGetTimecode
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeGetTransportMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeGetTransportMode
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativePlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativePlay
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeRewind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeRewind
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeFastForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeFastForward
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativePause
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeRecord
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeStepForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeStepForward
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_DVCamera
 * Method:    nativeStepBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_DVCamera_nativeStepBack
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
