/* Control Point Main Module */

/**
 * NOTE TO PUC IMPLEMENTORS:
 *
 * This is the file which has been modified to provide support for interaction between the code
 * generated by Intel Authoring Tools and the Java PUC Device code.  Primarily, the functions
 * with JNI-type names have been added; there are also a number of utilities which were added,
 * including the command queueing structure and methods, the JNI environment storage structure
 * and methods, and all other methods which do not begin with "UPnP" or "Java_".
 *
 * The header file CameraControl.h also has modifications, such as the JNI method headers.
 */

#include <jni.h>
#include "CameraControl.h"
#include <stdio.h>

#ifndef MICROSTACK_NO_STDAFX
#include "stdafx.h"
#endif
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <memory.h>
#include "UPnPControlPoint.h"
#include "ILibParsers.h"

// Generated variables for UPnP stack
void *UPnP_CP;
void *UPnP_CP_chain;

// Variable to check if the control point is currently running (i.e. capable of accepting commands)
short running;

/**
 * QueuedCommand Structs and Methods
 *
 * A problem encountered with the camera is that if several commands were received in rapid succession,
 * such as what happens when a scrollbar is dragged, the camera's response is very slow.  This is as a
 * result of the fact that each command is enqueued by the camera as it is received, so it will execute
 * a large number of sequential moves over small distances.
 *
 * To help avoid this problem, the QueuedCommand struct was introduced.  Now whenever a command is received,
 * the corresponded queuedXXX object has its commandInProg flag set to true.  Then any subsequent commands
 * result in the isQueued flag being set to true, and the queuedVal set to the most recent command's value.
 * Each QueuedCommand object also has a pointer to the setter function to be called when the command which
 * is in progress is completed.
 */

struct QueuedCommand {
	short commandInProg;
	short isQueued;
	int queuedVal;
	void (*setterFunc)(int);
} *queuedPan, *queuedTilt, *queuedZoom, *queuedPreset;

struct QueuedCommand *initQueuedCommand(void (*setterFunc)(int))
{
	struct QueuedCommand *qc = (struct QueuedCommand *) malloc(sizeof (struct QueuedCommand));
	qc->commandInProg = 0;
	qc->isQueued = 0;
	qc->setterFunc = setterFunc;
	return qc;
}

void dequeue(struct QueuedCommand *qc)
{
	qc->commandInProg = 0;
	if (qc->isQueued)
	{
		qc->isQueued = 0;
		qc->setterFunc(qc->queuedVal);
	}
}

/**
 * Stored background thread JNIEnv and UPnPControl pointers
 *
 * NOTE: These pointers are only good in the background thread (i.e., the one started by nativeStartCP).
 * Using them in any other thread will have unpredictable (but probably very bad) results.  The reason
 * for storing these pointer globally is so that they may be used by the event queuing methods to construct
 * and enqueue java-side UPnPEvents.
 */
struct {
	JNIEnv *bgEnv;
	jobject bgControl;
	jclass stateChangeCls;
	jmethodID stateChangeCtorMid;
	jclass stringResponseCls;
	jmethodID stringResponseCtorMid;
	jclass controlCls;
	jmethodID addEventMid;
} JNIData;

void fillJNIData(JNIEnv *env, jobject obj)
{
	JNIData.bgEnv = env;
	JNIData.bgControl = obj;
	JNIData.stateChangeCls = (*env)->FindClass(env, "edu/cmu/hcii/puc/devices/UPnP/UPnPEvent$StateChange");
	JNIData.stateChangeCtorMid = (*env)->GetMethodID(env, JNIData.stateChangeCls, "<init>",
		"(Ljava/lang/String;Ljava/lang/String;)V");
	JNIData.stringResponseCls = (*env)->FindClass(env, "edu/cmu/hcii/puc/devices/UPnP/UPnPEvent$StringResponse");
	JNIData.stringResponseCtorMid = (*env)->GetMethodID(env, JNIData.stringResponseCls, "<init>",
		"(ILjava/lang/String;)V");
	JNIData.controlCls = (*env)->GetObjectClass(env, obj);
	JNIData.addEventMid = (*env)->GetMethodID(env, JNIData.controlCls, "addEvent",
		"(Ledu/cmu/hcii/puc/devices/UPnP/UPnPEvent;)V");
}

void clearJNIData()
{
	memset(&JNIData, 0, sizeof(JNIData));
}

/**
 * Device List definition and manipulating functions.  This is not all that important for the camera, because
 * we only ever expect one such camera to be on the network.  For a more interesting application of the same
 * concept, see the Intel Light native code, which actually keeps track of all the lights on the network
 * (and is capable of sending commands to each one individually and simultaneously).
 */

typedef struct DeviceListEntry {
	struct UPnPDevice *device;
	struct UPnPService *Focus;
	struct UPnPService *Preset;
	struct UPnPService *PanTilt;
	struct DeviceListEntry *next;
} deviceListEntry;

deviceListEntry *listHead;

void addDevice(struct UPnPDevice *device)
{
	deviceListEntry *newEntry = (deviceListEntry *) malloc(sizeof(deviceListEntry));
	newEntry->device = device;
	newEntry->Focus = UPnPGetService_Focus(device);
	newEntry->Preset = UPnPGetService_Preset(device);
	newEntry->PanTilt = UPnPGetService_PanTilt(device);
	newEntry->next = listHead;
	listHead = newEntry;
}

deviceListEntry *getDevice(struct UPnPDevice *device)
{
	deviceListEntry *temp = listHead;
	while (temp != NULL && device != temp->device) temp = temp->next;
	return temp;
}

void removeDevice(struct UPnPDevice *device)
{
	deviceListEntry *temp = listHead;
	if (temp == NULL) return;
	else if (temp->device == device)
	{
		listHead = temp->next;
		free(temp);
		return;
	}

	while (temp->next != NULL && temp->next->device != device) temp = temp->next;
	if (temp->next != NULL)
	{
		deviceListEntry *next = temp->next;
		temp->next = temp->next->next;
		free(next);
	}
}

void cleanList()
{
	deviceListEntry *temp = listHead;
	while (temp != NULL)
	{
		deviceListEntry *next = temp->next;
		free(temp);
		temp = next;
	}
	listHead = NULL;
}

/**
 * Event Handling
 *
 * These methods construct UPnPEvent java object using JNI, and then add them to the corresponding
 * UPnPControl java object's event queue.  To understand exactly how these methods work, a
 * thorough understanding of JNI is required.  There are good resources for JNI on the Java website,
 * java.sun.com.
 */

void addPanEvent(int newPan)
{
	if (running)
	{
		jstring state;
		char valueBuf[5];
		jstring value;
		jobject panEvt;

		state = (*JNIData.bgEnv)->NewStringUTF(JNIData.bgEnv, "Pan");
		itoa(newPan, valueBuf, 10);
		value = (*JNIData.bgEnv)->NewStringUTF(JNIData.bgEnv, valueBuf);

		panEvt = (*JNIData.bgEnv)->NewObject(JNIData.bgEnv, JNIData.stateChangeCls,
			JNIData.stateChangeCtorMid, state, value);
		(*JNIData.bgEnv)->CallVoidMethod(JNIData.bgEnv, JNIData.bgControl, JNIData.addEventMid,
			panEvt);
	}
}

void addTiltEvent(int newTilt)
{
	if (running)
	{
		jstring state;
		char valueBuf[5];
		jstring value;
		jobject tiltEvt;

		state = (*JNIData.bgEnv)->NewStringUTF(JNIData.bgEnv, "Tilt");
		itoa(newTilt, valueBuf, 10);
		value = (*JNIData.bgEnv)->NewStringUTF(JNIData.bgEnv, valueBuf);

		tiltEvt = (*JNIData.bgEnv)->NewObject(JNIData.bgEnv, JNIData.stateChangeCls,
			JNIData.stateChangeCtorMid, state, value);
		(*JNIData.bgEnv)->CallVoidMethod(JNIData.bgEnv, JNIData.bgControl, JNIData.addEventMid,
			tiltEvt);
	}
}

void addZoomEvent(int newZoom)
{
	if (running)
	{
		jstring state;
		char valueBuf[5];
		jstring value;
		jobject zoomEvt;

		if (newZoom == 0) 
			newZoom = 1;

		state = (*JNIData.bgEnv)->NewStringUTF(JNIData.bgEnv, "Zoom");
		itoa(newZoom, valueBuf, 10);
		value = (*JNIData.bgEnv)->NewStringUTF(JNIData.bgEnv, valueBuf);

		zoomEvt = (*JNIData.bgEnv)->NewObject(JNIData.bgEnv, JNIData.stateChangeCls,
			JNIData.stateChangeCtorMid, state, value);
		(*JNIData.bgEnv)->CallVoidMethod(JNIData.bgEnv, JNIData.bgControl, JNIData.addEventMid,
			zoomEvt);
	}
}

void addPresetListEvent(char *presetList)
{
	if (running)
	{
		jint callingMethodID = (jint)METHOD_GET_PRESETS;
		jstring response;
		jobject presetEvt;

		response = (*JNIData.bgEnv)->NewStringUTF(JNIData.bgEnv, presetList);

		presetEvt = (*JNIData.bgEnv)->NewObject(JNIData.bgEnv, JNIData.stringResponseCls,
			JNIData.stringResponseCtorMid, callingMethodID, response);
		(*JNIData.bgEnv)->CallVoidMethod(JNIData.bgEnv, JNIData.bgControl, JNIData.addEventMid,
			presetEvt);
	}
}

// UPnP Event and Response Sinks

/**
 * NOTE:
 *
 * There is currently no error checking implemented here.  To make a fully robust solution, a means
 * should be derived to convey errors through the event queue.
 */


void UPnPResponseSink_Focus_SetAbsFocusPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: Focus/SetAbsFocusPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_Focus_SetRelZoomPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: Focus/SetRelZoomPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_Focus_SetAbsZoomPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	dequeue(queuedZoom);
	printf("UPnP Invoke Response: Focus/SetAbsZoomPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_Focus_GetIrisPosition(struct UPnPService* Service,int ErrorCode,void *User,unsigned int RetIrisSteps)
{
	printf("UPnP Invoke Response: Focus/GetIrisPosition[ErrorCode:%d](%u)\r\n",ErrorCode,RetIrisSteps);
}

void UPnPResponseSink_Focus_SetAbsIrisPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: Focus/SetAbsIrisPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_Focus_GetFocusPosition(struct UPnPService* Service,int ErrorCode,void *User,unsigned int RetFocusSteps)
{
	printf("UPnP Invoke Response: Focus/GetFocusPosition[ErrorCode:%d](%u)\r\n",ErrorCode,RetFocusSteps);
}

void UPnPResponseSink_Focus_GetZoomPosition(struct UPnPService* Service,int ErrorCode,void *User,unsigned int RetZoomSteps)
{
	if (User == (void *)GET_RESPONSE) addZoomEvent(RetZoomSteps);
	printf("UPnP Invoke Response: Focus/GetZoomPosition[ErrorCode:%d](%u)\r\n",ErrorCode,RetZoomSteps);
}

void UPnPResponseSink_Focus_SetRelIrisPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: Focus/SetRelIrisPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_Focus_SetRelFocusPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: Focus/SetRelFocusPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_Preset_GetPresetList(struct UPnPService* Service,int ErrorCode,void *User,char* RetPresetList)
{
	addPresetListEvent(RetPresetList);
	printf("UPnP Invoke Response: Preset/GetPresetList[ErrorCode:%d](%s)\r\n",ErrorCode,RetPresetList);
}

void UPnPResponseSink_Preset_RemovePreset(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: Preset/RemovePreset[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_Preset_GoToPreset(struct UPnPService* Service,int ErrorCode,void *User)
{
	dequeue(queuedPreset);
	printf("UPnP Invoke Response: Preset/GoToPreset[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_Preset_SetPreset(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: Preset/SetPreset[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_GetColorSaturation(struct UPnPService* Service,int ErrorCode,void *User,unsigned int RetColorSaturation)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/GetColorSaturation[ErrorCode:%d](%u)\r\n",ErrorCode,RetColorSaturation);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_SetBrightness(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/SetBrightness[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_GetFixedWhiteBalance(struct UPnPService* Service,int ErrorCode,void *User,unsigned int RetFixedWhiteBalance)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/GetFixedWhiteBalance[ErrorCode:%d](%u)\r\n",ErrorCode,RetFixedWhiteBalance);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_IncreaseBrightness(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/IncreaseBrightness[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_DecreaseBrightness(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/DecreaseBrightness[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_DecreaseColorSaturation(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/DecreaseColorSaturation[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_SetColorSaturation(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/SetColorSaturation[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_SetFixedWhiteBalance(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/SetFixedWhiteBalance[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_IncreaseColorSaturation(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/IncreaseColorSaturation[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraSettings_GetBrightness(struct UPnPService* Service,int ErrorCode,void *User,unsigned int RetBrightness)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraSettings/GetBrightness[ErrorCode:%d](%u)\r\n",ErrorCode,RetBrightness);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_SetDefaultCompressionLevel(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/SetDefaultCompressionLevel[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetAvailableEncodings(struct UPnPService* Service,int ErrorCode,void *User,char* RetAvailableEncodings)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetAvailableEncodings[ErrorCode:%d](%s)\r\n",ErrorCode,RetAvailableEncodings);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetImagePresentationURL(struct UPnPService* Service,int ErrorCode,void *User,char* RetImagePresentationURL)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetImagePresentationURL[ErrorCode:%d](%s)\r\n",ErrorCode,RetImagePresentationURL);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetAvailableResolutions(struct UPnPService* Service,int ErrorCode,void *User,char* RetAvailableResolutions)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetAvailableResolutions[ErrorCode:%d](%s)\r\n",ErrorCode,RetAvailableResolutions);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetImageURL(struct UPnPService* Service,int ErrorCode,void *User,char* RetImageURL)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetImageURL[ErrorCode:%d](%s)\r\n",ErrorCode,RetImageURL);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetDefaultImageURL(struct UPnPService* Service,int ErrorCode,void *User,char* RetImageURL)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetDefaultImageURL[ErrorCode:%d](%s)\r\n",ErrorCode,RetImageURL);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_SetDefaultEncoding(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/SetDefaultEncoding[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetAvailableCompressionLevels(struct UPnPService* Service,int ErrorCode,void *User,char* RetAvailableCompressionLevels)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetAvailableCompressionLevels[ErrorCode:%d](%s)\r\n",ErrorCode,RetAvailableCompressionLevels);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetDefaultEncoding(struct UPnPService* Service,int ErrorCode,void *User,char* RetEncoding)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetDefaultEncoding[ErrorCode:%d](%s)\r\n",ErrorCode,RetEncoding);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_SetDefaultResolution(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/SetDefaultResolution[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetDefaultCompressionLevel(struct UPnPService* Service,int ErrorCode,void *User,char* RetCompressionLevel)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetDefaultCompressionLevel[ErrorCode:%d](%s)\r\n",ErrorCode,RetCompressionLevel);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetDefaultImagePresentationURL(struct UPnPService* Service,int ErrorCode,void *User,char* RetImagePresentationURL)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetDefaultImagePresentationURL[ErrorCode:%d](%s)\r\n",ErrorCode,RetImagePresentationURL);
}

void UPnPResponseSink_DigitalSecurityCameraStillImage_GetDefaultResolution(struct UPnPService* Service,int ErrorCode,void *User,char* RetResolution)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraStillImage/GetDefaultResolution[ErrorCode:%d](%s)\r\n",ErrorCode,RetResolution);
}

void UPnPResponseSink_PanTilt_GetTiltPosition(struct UPnPService* Service,int ErrorCode,void *User,short RetTilt)
{
	if (User == (void *)GET_RESPONSE) addTiltEvent(RetTilt);
	printf("UPnP Invoke Response: PanTilt/GetTiltPosition[ErrorCode:%d](%d)\r\n",ErrorCode,RetTilt);
}

void UPnPResponseSink_PanTilt_GetPanPosition(struct UPnPService* Service,int ErrorCode,void *User,short RetPan)
{
	if (User == (void *)GET_RESPONSE) addPanEvent(RetPan);
	printf("UPnP Invoke Response: PanTilt/GetPanPosition[ErrorCode:%d](%d)\r\n",ErrorCode,RetPan);
}

void UPnPResponseSink_PanTilt_SetRelTiltPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: PanTilt/SetRelTiltPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_PanTilt_SetAbsTiltPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	dequeue(queuedTilt);
	printf("UPnP Invoke Response: PanTilt/SetAbsTiltPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_PanTilt_SetRelPanPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: PanTilt/SetRelPanPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_PanTilt_SetAbsPanPosition(struct UPnPService* Service,int ErrorCode,void *User)
{
	dequeue(queuedPan);
	printf("UPnP Invoke Response: PanTilt/SetAbsPanPosition[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetDefaultVideoPresentationURL(struct UPnPService* Service,int ErrorCode,void *User,char* RetVideoPresentationURL)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetDefaultVideoPresentationURL[ErrorCode:%d](%s)\r\n",ErrorCode,RetVideoPresentationURL);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_SetDefaultCompressionLevel(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/SetDefaultCompressionLevel[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetAvailableEncodings(struct UPnPService* Service,int ErrorCode,void *User,char* RetAvailableEncodings)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetAvailableEncodings[ErrorCode:%d](%s)\r\n",ErrorCode,RetAvailableEncodings);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetAvailableResolutions(struct UPnPService* Service,int ErrorCode,void *User,char* RetAvailableResolutions)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetAvailableResolutions[ErrorCode:%d](%s)\r\n",ErrorCode,RetAvailableResolutions);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetVideoURL(struct UPnPService* Service,int ErrorCode,void *User,char* RetVideoURL)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetVideoURL[ErrorCode:%d](%s)\r\n",ErrorCode,RetVideoURL);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_SetDefaultEncoding(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/SetDefaultEncoding[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetAvailableCompressionLevels(struct UPnPService* Service,int ErrorCode,void *User,char* RetAvailableCompressionLevels)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetAvailableCompressionLevels[ErrorCode:%d](%s)\r\n",ErrorCode,RetAvailableCompressionLevels);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetDefaultVideoURL(struct UPnPService* Service,int ErrorCode,void *User,char* RetVideoURL)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetDefaultVideoURL[ErrorCode:%d](%s)\r\n",ErrorCode,RetVideoURL);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetDefaultEncoding(struct UPnPService* Service,int ErrorCode,void *User,char* RetEncoding)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetDefaultEncoding[ErrorCode:%d](%s)\r\n",ErrorCode,RetEncoding);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_SetDefaultResolution(struct UPnPService* Service,int ErrorCode,void *User)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/SetDefaultResolution[ErrorCode:%d]()\r\n",ErrorCode);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetDefaultCompressionLevel(struct UPnPService* Service,int ErrorCode,void *User,char* RetCompressionLevel)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetDefaultCompressionLevel[ErrorCode:%d](%s)\r\n",ErrorCode,RetCompressionLevel);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetVideoPresentationURL(struct UPnPService* Service,int ErrorCode,void *User,char* RetVideoPresentationURL)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetVideoPresentationURL[ErrorCode:%d](%s)\r\n",ErrorCode,RetVideoPresentationURL);
}

void UPnPResponseSink_DigitalSecurityCameraMotionImage_GetDefaultResolution(struct UPnPService* Service,int ErrorCode,void *User,char* RetResolution)
{
	printf("UPnP Invoke Response: DigitalSecurityCameraMotionImage/GetDefaultResolution[ErrorCode:%d](%s)\r\n",ErrorCode,RetResolution);
}

void UPnPEventSink_Focus_IrisPosition(struct UPnPService* Service,unsigned int IrisPosition)
{
	printf("UPnP Event from %s/Focus/IrisPosition: %u\r\n",Service->Parent->FriendlyName,IrisPosition);
}

void UPnPEventSink_Focus_FocusPosition(struct UPnPService* Service,unsigned int FocusPosition)
{
	printf("UPnP Event from %s/Focus/FocusPosition: %u\r\n",Service->Parent->FriendlyName,FocusPosition);
}

void UPnPEventSink_Focus_ZoomPosition(struct UPnPService* Service,unsigned int ZoomPosition)
{
	if (Service->Parent == listHead->device) addZoomEvent(ZoomPosition);
	// printf("UPnP Event from %s/Focus/ZoomPosition: %u\r\n",Service->Parent->FriendlyName,ZoomPosition);
}

void UPnPEventSink_DigitalSecurityCameraSettings_Brightness(struct UPnPService* Service,unsigned int Brightness)
{
	printf("UPnP Event from %s/DigitalSecurityCameraSettings/Brightness: %u\r\n",Service->Parent->FriendlyName,Brightness);
}

void UPnPEventSink_DigitalSecurityCameraSettings_FixedWhiteBalance(struct UPnPService* Service,unsigned int FixedWhiteBalance)
{
	printf("UPnP Event from %s/DigitalSecurityCameraSettings/FixedWhiteBalance: %u\r\n",Service->Parent->FriendlyName,FixedWhiteBalance);
}

void UPnPEventSink_DigitalSecurityCameraSettings_ColorSaturation(struct UPnPService* Service,unsigned int ColorSaturation)
{
	printf("UPnP Event from %s/DigitalSecurityCameraSettings/ColorSaturation: %u\r\n",Service->Parent->FriendlyName,ColorSaturation);
}

void UPnPEventSink_DigitalSecurityCameraStillImage_DefaultResolution(struct UPnPService* Service,char* DefaultResolution)
{
	printf("UPnP Event from %s/DigitalSecurityCameraStillImage/DefaultResolution: %s\r\n",Service->Parent->FriendlyName,DefaultResolution);
}

void UPnPEventSink_DigitalSecurityCameraStillImage_DefaultEncoding(struct UPnPService* Service,char* DefaultEncoding)
{
	printf("UPnP Event from %s/DigitalSecurityCameraStillImage/DefaultEncoding: %s\r\n",Service->Parent->FriendlyName,DefaultEncoding);
}

void UPnPEventSink_DigitalSecurityCameraStillImage_DefaultCompressionLevel(struct UPnPService* Service,char* DefaultCompressionLevel)
{
	printf("UPnP Event from %s/DigitalSecurityCameraStillImage/DefaultCompressionLevel: %s\r\n",Service->Parent->FriendlyName,DefaultCompressionLevel);
}

void UPnPEventSink_PanTilt_TiltPosition(struct UPnPService* Service,short TiltPosition)
{
	if (Service->Parent == listHead->device) addTiltEvent(TiltPosition);
	// printf("UPnP Event from %s/PanTilt/TiltPosition: %d\r\n",Service->Parent->FriendlyName,TiltPosition);
}

void UPnPEventSink_PanTilt_PanPosition(struct UPnPService* Service,short PanPosition)
{
	if (Service->Parent == listHead->device) addPanEvent(PanPosition);
	// printf("UPnP Event from %s/PanTilt/PanPosition: %d\r\n",Service->Parent->FriendlyName,PanPosition);
}

void UPnPEventSink_DigitalSecurityCameraMotionImage_MaxBandwith(struct UPnPService* Service,unsigned int MaxBandwith)
{
	printf("UPnP Event from %s/DigitalSecurityCameraMotionImage/MaxBandwith: %u\r\n",Service->Parent->FriendlyName,MaxBandwith);
}

void UPnPEventSink_DigitalSecurityCameraMotionImage_DefaultResolution(struct UPnPService* Service,char* DefaultResolution)
{
	printf("UPnP Event from %s/DigitalSecurityCameraMotionImage/DefaultResolution: %s\r\n",Service->Parent->FriendlyName,DefaultResolution);
}

void UPnPEventSink_DigitalSecurityCameraMotionImage_DefaultEncoding(struct UPnPService* Service,char* DefaultEncoding)
{
	printf("UPnP Event from %s/DigitalSecurityCameraMotionImage/DefaultEncoding: %s\r\n",Service->Parent->FriendlyName,DefaultEncoding);
}

void UPnPEventSink_DigitalSecurityCameraMotionImage_DefaultCompressionLevel(struct UPnPService* Service,char* DefaultCompressionLevel)
{
	printf("UPnP Event from %s/DigitalSecurityCameraMotionImage/DefaultCompressionLevel: %s\r\n",Service->Parent->FriendlyName,DefaultCompressionLevel);
}

void UPnPEventSink_DigitalSecurityCameraMotionImage_TargetFrameRate(struct UPnPService* Service,unsigned int TargetFrameRate)
{
	printf("UPnP Event from %s/DigitalSecurityCameraMotionImage/TargetFrameRate: %u\r\n",Service->Parent->FriendlyName,TargetFrameRate);
}

/* Called whenever a new device on the correct type is discovered */
void UPnPDeviceDiscoverSink(struct UPnPDevice *device)
{
	struct UPnPDevice *tempDevice = device;
	struct UPnPService *tempService;
	
	/**
	 * The camera's implementation of this is very un-elegant.  It merely takes the newly
	 * discovered device, inserts it at the front of the list of devices on the network, and
	 * treats it as the only device from that point on.
	 * 
	 * For a more instructive means of dealing with multiple devices, see the Intel Light
	 * native code.
	 */

	addDevice(device);
	
	/* Subscribe for events on all services */
	while(tempDevice!=NULL)
	{
		tempService = tempDevice->Services;
		while(tempService!=NULL)
		{
			UPnPSubscribeForUPnPEvents(tempService,NULL);
			tempService = tempService->Next;
		}
		tempDevice = tempDevice->Next;
	}
}

/* Called whenever a discovered device was removed from the network */
void UPnPDeviceRemoveSink(struct UPnPDevice *device)
{
	removeDevice(device);
}

// Control methods
void getPan()
{
	if (running && listHead->PanTilt != NULL)
		UPnPInvoke_PanTilt_GetPanPosition(listHead->PanTilt, 
			&UPnPResponseSink_PanTilt_GetPanPosition, (void *)GET_RESPONSE);
}

void setPan(int newPan)
{
	if (running && listHead->PanTilt != NULL)
	{
		if (!queuedPan->commandInProg)
		{
			UPnPInvoke_PanTilt_SetAbsPanPosition(listHead->PanTilt, 
				&UPnPResponseSink_PanTilt_SetAbsPanPosition, (void *)GET_RESPONSE, (int)newPan);
			queuedPan->commandInProg = 1;
		}
		else
		{
			queuedPan->isQueued = 1;
			queuedPan->queuedVal = (int)newPan;
		}
	}
}

void getTilt()
{
	if (running && listHead->PanTilt != NULL)
		UPnPInvoke_PanTilt_GetTiltPosition(listHead->PanTilt, 
			&UPnPResponseSink_PanTilt_GetTiltPosition, (void *)GET_RESPONSE);
}

void setTilt(int newTilt)
{
	if (running && listHead->PanTilt != NULL)
	{
		if (!queuedTilt->commandInProg)
		{
		UPnPInvoke_PanTilt_SetAbsTiltPosition(listHead->PanTilt, 
			&UPnPResponseSink_PanTilt_SetAbsTiltPosition, (void *)GET_RESPONSE, (int)newTilt);
			queuedTilt->commandInProg = 1;
		}
		else
		{
			queuedTilt->isQueued = 1;
			queuedTilt->queuedVal = (int)newTilt;
		}
	}
}

void getZoom()
{
	if (running && listHead->Focus != NULL)
		UPnPInvoke_Focus_GetZoomPosition(listHead->Focus, 
			&UPnPResponseSink_Focus_GetZoomPosition, (void *)GET_RESPONSE);
}

void setZoom(int newZoom)
{
	if (running && listHead->Focus != NULL)
	{
		if (!queuedZoom->commandInProg)
		{
			UPnPInvoke_Focus_SetAbsZoomPosition(listHead->Focus, 
				&UPnPResponseSink_Focus_SetAbsZoomPosition, (void *)GET_RESPONSE, (int)newZoom);
			queuedZoom->commandInProg = 1;
		}
		else
		{
			queuedZoom->isQueued = 1;
			queuedZoom->queuedVal = (int)newZoom;
		}
	}
}

void goToPreset(int presetNum)
{
	if (running && listHead->Preset != NULL)
	{
		if (!queuedPreset->commandInProg)
		{
			UPnPInvoke_Preset_GoToPreset(listHead->Preset, &UPnPResponseSink_Preset_GoToPreset, 
				(void *)IGNORE_RESPONSE, (int)presetNum);
			queuedPreset->commandInProg = 1;
		}
		else
		{
			queuedPreset->isQueued = 1;
			queuedPreset->queuedVal = (int)presetNum;
		}
	}
}

// Java native method implementations

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeInit
  (JNIEnv *env, jobject obj)
{
	/* Event callback function registration code */
	// UPnPEventCallback_Focus_IrisPosition=&UPnPEventSink_Focus_IrisPosition;
	// UPnPEventCallback_Focus_FocusPosition=&UPnPEventSink_Focus_FocusPosition;
	UPnPEventCallback_Focus_ZoomPosition=&UPnPEventSink_Focus_ZoomPosition;
	// UPnPEventCallback_DigitalSecurityCameraSettings_Brightness=&UPnPEventSink_DigitalSecurityCameraSettings_Brightness;
	// UPnPEventCallback_DigitalSecurityCameraSettings_FixedWhiteBalance=&UPnPEventSink_DigitalSecurityCameraSettings_FixedWhiteBalance;
	// UPnPEventCallback_DigitalSecurityCameraSettings_ColorSaturation=&UPnPEventSink_DigitalSecurityCameraSettings_ColorSaturation;
	// UPnPEventCallback_DigitalSecurityCameraStillImage_DefaultResolution=&UPnPEventSink_DigitalSecurityCameraStillImage_DefaultResolution;
	// UPnPEventCallback_DigitalSecurityCameraStillImage_DefaultEncoding=&UPnPEventSink_DigitalSecurityCameraStillImage_DefaultEncoding;
	// UPnPEventCallback_DigitalSecurityCameraStillImage_DefaultCompressionLevel=&UPnPEventSink_DigitalSecurityCameraStillImage_DefaultCompressionLevel;
	UPnPEventCallback_PanTilt_TiltPosition=&UPnPEventSink_PanTilt_TiltPosition;
	UPnPEventCallback_PanTilt_PanPosition=&UPnPEventSink_PanTilt_PanPosition;
	// UPnPEventCallback_DigitalSecurityCameraMotionImage_MaxBandwith=&UPnPEventSink_DigitalSecurityCameraMotionImage_MaxBandwith;
	// UPnPEventCallback_DigitalSecurityCameraMotionImage_DefaultResolution=&UPnPEventSink_DigitalSecurityCameraMotionImage_DefaultResolution;
	// UPnPEventCallback_DigitalSecurityCameraMotionImage_DefaultEncoding=&UPnPEventSink_DigitalSecurityCameraMotionImage_DefaultEncoding;
	// UPnPEventCallback_DigitalSecurityCameraMotionImage_DefaultCompressionLevel=&UPnPEventSink_DigitalSecurityCameraMotionImage_DefaultCompressionLevel;
	// UPnPEventCallback_DigitalSecurityCameraMotionImage_TargetFrameRate=&UPnPEventSink_DigitalSecurityCameraMotionImage_TargetFrameRate;

	listHead = NULL;
	running = 0;

	queuedPan = initQueuedCommand(&setPan);
	queuedTilt = initQueuedCommand(&setTilt);
	queuedZoom = initQueuedCommand(&setZoom);
	queuedPreset = initQueuedCommand(&goToPreset);
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeStartCP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeStartCP
  (JNIEnv *env, jobject obj)
{
	UPnP_CP_chain = ILibCreateChain();
	UPnP_CP = UPnPCreateControlPoint(UPnP_CP_chain,&UPnPDeviceDiscoverSink,&UPnPDeviceRemoveSink);

	cleanList();
	fillJNIData(env, obj);

	running = 1;
	printf("PUC Camera Control Point 1.0 Started\r\n");
	ILibStartChain(UPnP_CP_chain);
	printf("PUC Camera Control Point 1.0 Stopped\r\n");
	running = 0;

	clearJNIData();
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeStopCP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeStopCP
  (JNIEnv *env, jobject obj)
{
	if (running)
		ILibStopChain(UPnP_CP_chain);
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeGetPan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeGetPan
  (JNIEnv *env, jobject obj)
{
	printf("Called nativeGetPan\n");
	getPan();
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeSetPan
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeSetPan
  (JNIEnv *env, jobject obj, jint newPan)
{
	printf("Called nativeSetPan\n");
	setPan((int)newPan);
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeGetTilt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeGetTilt
  (JNIEnv *env, jobject obj)
{
	printf("Called nativeGetTilt\n");
	getTilt();
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeSetTilt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeSetTilt
  (JNIEnv *env, jobject obj, jint newTilt)
{
	printf("Called nativeSetTilt\n");
	setTilt((int)newTilt);
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeGetZoom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeGetZoom
  (JNIEnv *env, jobject obj)
{
	printf("Called nativeGetZoom\n");
	getZoom();
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeSetZoom
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeSetZoom
  (JNIEnv *env, jobject obj, jint newZoom)
{
	printf("Called nativeSetZoom\n");
	setZoom((int)newZoom);
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeGetPresets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeGetPresets
  (JNIEnv *env, jobject obj)
{
	printf("Called nativeGetPresets\n");
	UPnPInvoke_Preset_GetPresetList(listHead->Preset, &UPnPResponseSink_Preset_GetPresetList, 
		(void *)GET_RESPONSE);
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeGoToPreset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeGoToPreset
  (JNIEnv *env, jobject obj, jint presetNum)
{
	printf("Called nativeGoToPreset\n");
	goToPreset((int)presetNum);
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeSetPreset
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeSetPreset
  (JNIEnv *env, jobject obj, jint presetNum, jstring presetName)
{
	printf("nativeSetPreset not implemented\n");
}

/*
 * Class:     edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl
 * Method:    nativeRemovePreset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_UPnP_AxisCamera_CameraControl_nativeRemovePreset
  (JNIEnv *env, jobject obj, jint presetNum)
{
	printf("nativeRemovePreset not implemented\n");
}

