/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_hcii_puc_devices_X10Lamp */

#ifndef _Included_edu_cmu_hcii_puc_devices_X10Lamp
#define _Included_edu_cmu_hcii_puc_devices_X10Lamp
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_cmu_hcii_puc_devices_X10Lamp_baud_rate
#define edu_cmu_hcii_puc_devices_X10Lamp_baud_rate 4800L
/*
 * Class:     edu_cmu_hcii_puc_devices_X10Lamp
 * Method:    native_open_serial_port
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_X10Lamp_native_1open_1serial_1port
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_cmu_hcii_puc_devices_X10Lamp
 * Method:    native_close_serial_port
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_X10Lamp_native_1close_1serial_1port
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_X10Lamp
 * Method:    native_Handle_X10_Device
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_X10Lamp_native_1Handle_1X10_1Device
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     edu_cmu_hcii_puc_devices_X10Lamp
 * Method:    native_Execute_command
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_X10Lamp_native_1Execute_1command
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     edu_cmu_hcii_puc_devices_X10Lamp
 * Method:    native_Prime_X10_Interface
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_cmu_hcii_puc_devices_X10Lamp_native_1Prime_1X10_1Interface
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_X10Lamp
 * Method:    native_read_x10_status
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_hcii_puc_devices_X10Lamp_native_1read_1x10_1status
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
