package edu.cmu.hcii.puc.devices.elevator;

/**
 * Any Exception which can be generated by an Elevator should extend
 * this base class.  This allows for easier exception type handling.
 */
public class ElevatorException extends Exception
{

  public ElevatorException() { super(); }
  public ElevatorException(String msg) { super(msg); }

  public static class DoorClosedException extends ElevatorException
  {
    public DoorClosedException() { super(); }
    public DoorClosedException(String msg) { super(msg); }
  }

  public static class WrongFloorException extends ElevatorException
  {
    public WrongFloorException() { super(); }
    public WrongFloorException(String msg) { super(msg); }
  }

  public static class NoRoomException extends ElevatorException
  {
    public NoRoomException() { super(); }
    public NoRoomException(String msg) { super(msg); }
  }

}