/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_hcii_puc_devices_WinampDevice */

#ifndef _Included_edu_cmu_hcii_puc_devices_WinampDevice
#define _Included_edu_cmu_hcii_puc_devices_WinampDevice
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: name */
#undef edu_cmu_hcii_puc_devices_WinampDevice_MODE_PLAY
#define edu_cmu_hcii_puc_devices_WinampDevice_MODE_PLAY 1L
#undef edu_cmu_hcii_puc_devices_WinampDevice_MODE_PAUSE
#define edu_cmu_hcii_puc_devices_WinampDevice_MODE_PAUSE 2L
#undef edu_cmu_hcii_puc_devices_WinampDevice_MODE_STOP
#define edu_cmu_hcii_puc_devices_WinampDevice_MODE_STOP 3L
/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    prevTrack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_prevTrack
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_play
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_pause
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    stopPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_stopPlay
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    nextTrack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_nextTrack
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    stopAfterCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_stopAfterCurrent
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    fadeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_fadeStop
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    volumeUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_volumeUp
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    volumeDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_volumeDown
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    setVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_setVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    toggleShuffle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_toggleShuffle
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    toggleLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_toggleLoop
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    seek
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_seek
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    setPlaylistPos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_setPlaylistPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    setPanning
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_setPanning
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    winampVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_winampVersion
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    playlistLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_playlistLength
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    playbackStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_playbackStatus
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    currentTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_currentTitle
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    outputTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_outputTime
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    songLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_songLength
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    posInPlaylist
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_posInPlaylist
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    isShuffling
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_isShuffling
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_hcii_puc_devices_WinampDevice
 * Method:    isLooping
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_hcii_puc_devices_WinampDevice_isLooping
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
